name: vproduce
description: A e-commerce app for agriculture products.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.5
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans-Bold.ttf
        - asset: fonts/GoogleSans-BoldItalic.ttf
        - asset: fonts/GoogleSans-Italic.ttf
        - asset: fonts/GoogleSans-Medium.ttf
        - asset: fonts/GoogleSans-MediumItalic.ttf
        - asset: fonts/GoogleSans-Regular.ttf
